### ISSUE TITLE
Ability to animate item only one-way

### ISSUE THREAD

**Issue by joshcawthorne** [jeffersonlicet/react-motion-layout#5]
Is there any way to skip animation when a user navigates back? The way I'm using this library means that the return animation often looks quite janky due to the way data is sometimes re-loaded between component change. I'd love for a way to run the animation on enter, but not on exit!

**Comment by jeffersonlicet** [comment]
Hi Josh, thanks for taking a look at RML.
I'm sending a PR today to add this ability.

**Comment by joshcawthorne** [comment]
Awesome, great to hear!

**Comment by jeffersonlicet** [comment]
Closed + new version supporting this. react-motion-layout@0.1.3
[Commit](https://github.com/jeffersonlicet/react-motion-layout/commit/fd0759c5b016082475f5673db73e474d811734fb)

Please feel free to reopen it if you have any comments.

Thanks for the feedback.
